### ISSUE TITLE
Start with all fields in edit mode.

### ISSUE THREAD

**Issue by almet** [Kinto/formbuilder#10]
I think it could be useful to have the fields in edit mode as soon as they are added. I did some testing and changing `edit` to `true` by default isn't enough because the state isn't persisted.

What do you think about storing this information in the store and passing it as props rather than having the component directly handle this with state? Otherwise the default value will always come back (currently, if you are in edition and add a new field then the field you were editing will come back to the edit:false state).

**Comment by n1k0** [comment]
Not sure about the editing mode enabled by default, but moving editing state to store sounds like something worthy. Could you come with a patch?

**Comment by almet** [comment]
I wanted to double check that with you first, so nope.

About editing mode by default, that's my use case for all the times I use the form builder: I want to add a field and edit it right away.

**Comment by n1k0** [comment]
Really depends on one's prefered flow; I usually drag all the field I need then start customizing them :/

**Comment by almet** [comment]
Oh interesting. We should decide one way or the other. I felt that would be a good change. Maybe can we add a configuration value for this?

**Comment by almet** [comment]
I would love to see some feedback from UX experts here :) @QuentinRoy ?

**Comment by QuentinRoy** [comment]
In any case, adding a configuration value does not save you from making the best choice a default. I emphasise this point because this is important and a mistake that, as power users, we are likely to do. Users are not designers.
So, you identified two different workflows. These two workflows seem to address two different type of users:
1. The "planner": add all (or a bunch?) of widgets then edit them.
2. The "builder": add and set up fully a widget before going to the next one.
Sometimes it is OK to focus on one workflows so that you can better optimise it but it doesn't seem to be a good idea here. I do not think there is much performance difference between the two workflows (I may be wrong), they address two different type of users and you probably want to make your system usable by both.
I do not have the time to think about the needs of each one of them, but it seems that the "planner" will need a fast way to make multiple widgets selection while the "builder" will need a way to rapidly switch between widget selection and edition. So currently you interaction syntax favours the "planner".

You can try to activate the "edit" mode after addition, but only for the last added widget (i.e. disable it as soon as a new one is added).
If a field is in "edit" mode after its addition, it will make the "builder" faster as he won't have to click each time on the edit button. However, it may annoy the "planner" because the edition mode is very different to the "final" mode (it may not be a good idea to improve this by the way, wysiwyg and so on), and so, it may be a bit more harder for him to visualise his progress. This is especially true if all widgets remain in edit mode but I suspect it will be much less annoying if it is only the case for the last one (his selection will still be on his working memory anyway). And because the "builder" create his widget one by one, he doesn't really need to have more than one in edit mode anyway, and like that he may even skip the "submit" step.

**Comment by almet** [comment]
I'm putting this in v2 as I don't want to block on this to release v1.

**Comment by n1k0** [comment]
After an UX review at SudWeb, we agreed that this should actually be the default behavior.

**Comment by almet** [comment]
Implemented!
