### ISSUE TITLE
Multiple choices: checkboxes

### ISSUE THREAD

**Issue by leplatrem** [Kinto/formbuilder#7]

**Comment by n1k0** [comment]
You should find this on react-jsonschema-form as well ;)
Le 18 janv. 2016 9:53 AM, "Mathieu Leplatre" <notifications@github.com> a
écrit :

**Comment by almet** [comment]
See https://github.com/mozilla-services/react-jsonschema-form/issues/41 for the support of multiple values selects. This is currently displayed as a multi select, and not via checkboxes, though.

I haven't found any current way to do this in the documentation of react-json-schema-form, so I believe it would take us to add a new component to the react-json-schema-form library in order to display this list as multiple checkboxes.

**Comment by almet** [comment]
See https://github.com/mozilla-services/react-jsonschema-form/pull/222

**Comment by glasserc** [comment]
I'd also be interested in this for the purposes of a "Select all that apply" question.

**Comment by almet** [comment]
Hey @n1k0, as you're the RJSF expert around here, could you give it a try when/if you find some time for it? Thanks!

**Comment by n1k0** [comment]
Attempt is being made in #182 :)

**Comment by n1k0** [comment]
Fixed by #182.
